swagger_ui:
    path: /api/doc
    controller: api_platform.swagger.action.ui

index:
    path: /
    controller: App\Controller\DefaultController::index

api_platform.swagger_ui:
    resource: .
    type: api_platform
    prefix: /api


oauth2_authorize:
    path: /api/authorize
    controller: ['league.oauth2_server.controller.authorization', 'indexAction']

oauth2_token:
    path: /oauth/v2/token
    controller: ['league.oauth2_server.controller.token', 'indexAction']

