parameters:
    base_url: 'https://dev.events.portable'
    router.request_context.host: 'dev.events.portable'
    main_host: dev.events.portable
    host_map:
        localhost: 'www.24h-emploi-formation.com'
        dev.events.portable: 'www.24h-emploi-formation.com'
        48h.master.events.local: 'www.48h-emploi-formation.com'
        experts.master.events.local: 'www.recrutementexperts.fr'
        escape.master.events.local: 'www.escapegamerecrut.fr'
        comedy.master.events.local: 'www.recrutcomedyclub.fr'